services:
  postgres:
    image: postgres:13
    environment:
      POSTGRES_USER: ccardoso
      POSTGRES_PASSWORD: ccardoso
      POSTGRES_HOST: postgres
      POSTGRES_DB: bronze
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

volumes:
  pgdata:
