test_profile:
  target: dev
  outputs:
    dev:
      type: postgres
      host: 172.18.0.2
      user: ccardoso
      password: ccardoso
      port: 5432
      dbname: develop
      schema: public
      threads: 1