services:
  postgres:
    image: postgres:13
    environment:
      POSTGRES_USER: ccardoso
      POSTGRES_PASSWORD: ccardoso
      POSTGRES_HOST: postgres
      POSTGRES_DB: bronze
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
    volumes:
      - pgdata:/var/lib/postgresql/data
  dbt:
    container_name: dbt
    build: .
    image: dbt-dummy
    volumes:
      - ./:/usr/src/dbt
    depends_on:
      postgres:
        condition: service_healthy
volumes:
  pgdata:

