test_profile:
  target: dev
  outputs:
    dev:
      type: postgres
      host: localhost
      user: ccardoso
      password: ccardoso
      port: 5432
      dbname: bronze
      schema: public
      threads: 1